---
title: "PRJNA335425_PS"
author: "Bryshal Moore"
date: "2026-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Libraries
```{r}
library(phyloseq); packageVersion("phyloseq")
```

```{r}
library(Biostrings); packageVersion("Biostrings")
```

```{r}
library(ggplot2); packageVersion("ggplot2")
```
```{r}
getwd()
```

### Load Sequence Table
```{r}
seq_tab <- read.csv("sequence_table.csv", row.names = 1, check.names = FALSE) # Change to location of sequence table
```

### Load the taxonomy table
```{r}
taxa_id <- read.csv("taxid.csv", row.names = 1, check.names = FALSE)

head(taxa_id)
```
### Load the metadata
```{r}
meta_data <- read.csv("SraRunTable.csv", row.names = 1, header = T, check.names = FALSE)
head(meta_data)
```

### Transpose the sequence table
```{r}
# Transpose the sequence table
seq_tab_t <- t(seq_tab)

head(seq_tab_t)
```

```{}
# Extract sequences from rownames and replace with ASV IDs
seqs <- DNAStringSet(rownames(seq_tab_t))
names(seqs) <- paste0("ASV", seq(1, nrow(seq_tab_t)))
```

```{}
# Replace sequence rownames with ASV IDs
rownames(seq_tab_t) <- paste0("ASV", seq(1, nrow(seq_tab_t)))
```


```{}
# Verify
dim(seq_tab_t)          # rows = ASVs, cols = samples
head(rownames(seq_tab_t))  # should show ASV1, ASV2...
head(colnames(seq_tab_t))  # should show sample names
seqs                    # DNAStringSet with ASV sequences
```

```{}
# Save the sequences as a fasta file
writeXStringSet(seqs, filepath = "ASVs.fasta")

```

```{}

# Save the transposed table
write.csv(seq_tab_t, file = "seq_table_transposed.csv")
```


### Construct the Phyloseq Object

```{r}
# They should all match
rownames(seq_tab_t)   
```

```{r}
rownames(taxa_id)     # should also be same sequences
```

```{r}
rownames(meta_data)   # should be sample names e.g. SRR5515450...
```

```{r}
colnames(seq_tab_t)   # should also be sample names
```
```{r}
class(seq_tab_t)    # should be "matrix"
class(meta_data)  # should be "data.frame"
class(taxa_id)       # should be "matrix"
```
```{r}

# Quick check - should return TRUE
all(rownames(meta_data) %in% rownames(seq_tab))
all(rownames(seq_tab) %in% rownames(meta_data))
```
```{r}
# OTU table taxa - should be sequences
head(colnames(seq_tab))

# Tax table taxa - should also be sequences
head(rownames(taxa_id))

# Are they identical?
all(colnames(seq_tab) == rownames(taxa_id))
```

```{r}
# Check all three objects explicitly
dim(seq_tab)
dim(taxa_id)
dim(meta_data)
```


```{r}
# Check names
head(colnames(seq_tab))    # taxa in otu table
```

```{r}
head(rownames(taxa_id))    # taxa in tax table
```

```{r}
# Are they exactly equal?
identical(colnames(seq_tab), rownames(taxa_id))
```

```{r}
# Check sample names
identical(rownames(seq_tab), rownames(meta_data))
```
### Troubeshooting with AI

```{r}
# Detach and reload phyloseq
detach("package:phyloseq", unload=TRUE)
library(phyloseq)
```



```{r}
# Build each component separately first
OTU <- otu_table(seq_tab, taxa_are_rows = FALSE)
SAM <- sample_data(meta_data)
TAX <- tax_table(as.matrix(taxa_id))
```


```{r}
# Check each component individually
taxa_names(OTU) |> head()
taxa_names(TAX) |> head()
sample_names(OTU)
sample_names(SAM)
```

```{r}
ps <- phyloseq(OTU, SAM, TAX)
ps
```
```{r}
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps
```
```{r}
refseq(ps)
```


```{ls}
# Save ASVs as fasta file
Biostrings::writeXStringSet(refseq(ps), filepath = "/home/brymoore/wsg_gtdb_tax/pig_microbiome/PRJNA335425/ASV.fasta")
```

