---
title: "Pig_Microbiome_ASV_V_Region"
author: "Bryshal Moore"
date: "2026-08-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load Library
```{r}
### Load Libraries

library(tidyverse)
library(dplyr)
library(phyloseq)
library(data.table)
library(purrr)
library(Biostrings)
library(stringr)
library(readr)
library(janitor)
```



## Read the Phyloseq Object
```{r}
ps_asv <- readRDS("ps_genus.rds")
```

```{r}
ps_otu <- readRDS("ps_v_genus.rds")
```

## Read the master_metadata file
```{r}
metdat <- read.csv("master_metadata.csv", row.names = 1 )
```


## Extract the tables
```{r}
otu <- as.data.frame(otu_table(ps_asv))
```

```{r}
tax <- as.data.frame(tax_table(ps_asv))
```


## Recreate the ps_asv object

```{r}
OTU <- otu_table(as.matrix(otu), taxa_are_rows = T)
TAX <- tax_table(as.matrix(tax))

ps_asv <- phyloseq(OTU, TAX, metdat)
```

```{r}
if (!taxa_are_rows(ps_asv)) otu <- t(otu)
```

```{r}
metdat$sample <- rownames(metdat)
```


## Build the Genus x study presence table
```{r}
otu_long <- otu |> 
  as.data.frame() |> 
  mutate(genus = tax$genus[match(rownames(otu), rownames(tax))]) %>%
  pivot_longer(-genus, names_to = "sample", values_to = "count") %>%
  left_join(metdat, by = "sample")


```

```{r}
genus_study_presence <- otu_long %>%
  group_by(genus, study, variable_region) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
head(genus_study_presence)
```


## Strict core
```{r}
n_studies <- n_distinct(metdat$study)
```

```{r}
core_genera_strict <- genus_study_presence %>%
  group_by(genus) %>%
  summarise(n_studies_present = sum(present)) %>%
  filter(n_studies_present == n_studies)
```

```{r}
core_genera_strict
```

## Threshold of 60%

```{r}
threshold <- 0.60

core_genera_relaxed <- genus_study_presence %>%
  group_by(genus) %>%
  summarise(n_studies_present = sum(present),
            prop_studies = n_studies_present / n_studies) %>%
  filter(prop_studies >= threshold) %>%
  arrange(desc(prop_studies))

core_genera_relaxed
```





## Body Site

```{r}
genus_site_presence <- otu_long %>%
  group_by(genus, bodysite_standard) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_site <- n_distinct(metdat$bodysite_standard)
```

```{r}
core_genera_site <- genus_site_presence %>%
  group_by(genus) %>%
  summarise(n_site_present = sum(present),
            prop_site = n_site_present / n_site) %>%
  filter(prop_site >= 0.50) %>%
  arrange(desc(prop_site))

core_genera_site
```


## individual and bodysite

```{r}
genus_ibs_presence <- otu_long %>%
  group_by(genus, specific_identifier, bodysite_standard, variable_region) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_ibs <- metdat |> 
  distinct(bodysite_standard, specific_identifier, variable_region) |> 
  nrow()
```



```{r}
core_genera_ibs <- genus_ibs_presence %>%
  group_by(genus) %>%
  summarise(n_present = sum(present),
            prop= n_present / n_ibs) %>%
  filter(prop >= 0.50) %>%
  arrange(desc(prop))

core_genera_ibs
```

## Site Specific Core


```{r}
core_genera_by_site <- genus_ibs_presence %>%
  group_by(bodysite_standard, genus) %>%
  summarise(n_individuals_present = sum(present),
            n_individuals_total = n_distinct(specific_identifier),
            prop_individuals = n_individuals_present / n_individuals_total,
            .groups = "drop") %>%
  filter(prop_individuals >= 0.50) %>%
  arrange(bodysite_standard, desc(prop_individuals))

core_genera_by_site
```

```{r}
metdat |> 
  count(bodysite_standard)
```

```{r}
core_genera_by_site |> 
  filter(bodysite_standard == "cecum")
```

```{r}
core_genera_by_site |> 
  filter(bodysite_standard == "colon")
```

```{r}
split_by_site <- function(df, site_col = "bodysite_standard") {
  sites <- unique(df[[site_col]])
  
  for (s in sites) {
    obj_name <- paste0("core_genera_", make.names(s))  # sanitizes spaces/special chars
    assign(obj_name, df %>% filter(.data[[site_col]] == s), envir = .GlobalEnv)
  }
  
  message(paste("Created objects:", paste0("core_genera_", make.names(sites), collapse = ", ")))
}

split_by_site(core_genera_by_site)

# makes core_genera_colon, core_genera_cecum
core_genera_colon
```

## Hypervariable Region Evaluation

```{r}
genus_region_presence <- otu_long %>%
  group_by(genus, variable_region) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
head(genus_region_presence)
```

```{r}
core_genera_regions <- genus_region_presence %>%
  filter(present == TRUE) %>%
  filter(genus %in% core_genera_relaxed$genus) %>%
  group_by(genus) %>%
  summarise(regions_detected = paste(sort(unique(variable_region)), collapse = ", "),
            n_regions = n_distinct(variable_region), .groups = "drop") %>%
  arrange(desc(n_regions))

core_genera_regions
```

```{r}
core_genera_by_site_regions <- core_genera_by_site %>%
  left_join(
    otu_long %>%
      filter(count > 0) %>%
      distinct(genus, bodysite_standard, variable_region),
    by = c("genus", "bodysite_standard")
  ) %>%
  group_by(bodysite_standard, genus) %>%
  summarise(regions_detected = paste(sort(unique(variable_region)), collapse = ", "),
            n_regions = n_distinct(variable_region),
            .groups = "drop") %>%
  arrange(bodysite_standard, desc(n_regions))

core_genera_by_site_regions
```
```{r}
split_by_site_region <- function(df, site_col = "bodysite_standard") {
  sites <- unique(df[[site_col]])
  
  for (s in sites) {
    obj_name <- paste0("region_genera_", make.names(s))  # sanitizes spaces/special chars
    assign(obj_name, df %>% filter(.data[[site_col]] == s), envir = .GlobalEnv)
  }
  
  message(paste("Created objects:", paste0("region_genera_", make.names(sites), collapse = ", ")))
}

split_by_site_region(core_genera_by_site_regions)
```



```{r}
# the genra that are only found in on hypervariable region
core_genera_regions %>%
  filter(n_regions == 1)
```


```{r}
core_region_matrix <- genus_region_presence %>%
  filter(genus %in% core_genera_relaxed$genus) %>%
  pivot_wider(names_from = variable_region, values_from = present, values_fill = FALSE)

core_region_matrix
```
## Variable Region Data Table Redo

## Body Site

```{r}
genus_site_presence <- otu_long %>%
  group_by(genus, bodysite_standard) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_site <- n_distinct(metdat$bodysite_standard)
```

```{r}
core_genera_site <- genus_site_presence %>%
  group_by(genus) %>%
  summarise(n_site_present = sum(present),
            prop_site = n_site_present / n_site) %>%
  filter(prop_site >= 0.50) %>%
  arrange(desc(prop_site))

core_genera_site
```


```{r}
genus_region_presence <- otu_long %>%
  group_by(genus, variable_region, study, treatment, bodysite_standard, sequencing_type, sample) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
head(genus_region_presence)
```

```{r}
total_per_region_site <- genus_region_presence %>%
  filter(!is.na(variable_region)) %>%
  group_by(variable_region, bodysite_standard) %>%
  summarise(total_individuals = n_distinct(sample), .groups = "drop")
```

```{r}
core_genus_region_prop <- genus_region_presence %>%
  filter(present == TRUE) %>%
  filter(!is.na(variable_region)) %>%
  filter(genus %in% core_genera_relaxed$genus) %>%
  group_by(genus, variable_region, bodysite_standard) %>%
  summarise(n_individual = n_distinct(sample), .groups = "drop") %>% 
  left_join(total_per_region_site, by = c("variable_region", "bodysite_standard")) %>%
  mutate(prop_individuals = (n_individual / total_individuals) * 100) %>%
  arrange(genus)


head(core_genus_region_prop)
```

```{}
write_csv(core_genus_region_prop, "core_genus_region_prop.csv")
```



```{}
write_csv(region_genera_cecum, "asv_variable_cecum.csv")
write_csv(region_genera_digesta, "asv_variable_digesta.csv")
write_csv(region_genera_colon, "asv_variable_colon.csv")
write_csv(region_genera_duodenum, "asv_variable_duodenum.csv")
write_csv(region_genera_feces, "asv_variable_feces.csv")
write_csv(region_genera_ileum, "asv_variable_ileum.csv")
write_csv(region_genera_jejunum, "asv_variable_jejunum.csv")
write_csv(region_genera_mucosa, "asv_variable_mucosa.csv")
```

```{}
write_csv(core_genera_regions, "asv_core_genra_variables.csv")
```



