---
title: Pig_Cores_OTU
author: "Bryshal Moore"
date: "2026-08-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Library
```{r}
### Load Libraries

library(tidyverse)
library(dplyr)
library(phyloseq)
library(data.table)
library(purrr)
library(Biostrings)
library(stringr)
library(readr)
library(janitor)
```



## Read the Phyloseq Object
```{r}
ps_asv <- readRDS("ps_genus.rds")
```

```{r}
ps_otu <- readRDS("ps_v_genus.rds")
```

## Read the master_metadata file
```{r}
metdat <- read.csv("master_metadata.csv", row.names = 1 )
```


## Extract the tables
```{r}
otu <- as.data.frame(otu_table(ps_asv))
```

```{r}
tax <- as.data.frame(tax_table(ps_asv))
```


## Recreate the ps_otu object

```{r}
OTU <- otu_table(as.matrix(otu), taxa_are_rows = T)
TAX <- tax_table(as.matrix(tax))

ps_asv <- phyloseq(OTU, TAX, metdat)
```

```{r}
if (!taxa_are_rows(ps_asv)) otu <- t(otu)
```

```{r}
metdat$sample <- rownames(metdat)
```


## Build the Genus x study presence table
```{r}
otu_long <- otu |> 
  as.data.frame() |> 
  mutate(genus = tax$genus[match(rownames(otu), rownames(tax))]) %>%
  pivot_longer(-genus, names_to = "sample", values_to = "count") %>%
  left_join(metdat, by = "sample")


```

```{r}
genus_study_presence <- otu_long %>%
  group_by(genus, study) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

## Strict core
```{r}
n_studies <- n_distinct(metdat$study)
```

```{r}
core_genera_strict <- genus_study_presence %>%
  group_by(genus) %>%
  summarise(n_studies_present = sum(present)) %>%
  filter(n_studies_present == n_studies)
```

```{r}
core_genera_strict
```

## Threshold of 80%

```{r}
threshold <- 0.80

core_genera_relaxed <- genus_study_presence %>%
  group_by(genus) %>%
  summarise(n_studies_present = sum(present),
            prop_studies = n_studies_present / n_studies) %>%
  filter(prop_studies >= threshold) %>%
  arrange(desc(prop_studies))

core_genera_relaxed
```

## Variable Region
```{r}
genus_variable_presence <- otu_long %>%
  group_by(genus, variable_region) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_studies_variable <- n_distinct(metdat$variable_region)
```

```{r}
core_genera_variable <- genus_variable_presence %>%
  group_by(genus) %>%
  summarise(n_variables_present = sum(present),
            prop_studies = n_variables_present / n_studies_variable) %>%
  filter(prop_studies >= threshold) %>%
  arrange(desc(prop_studies))

core_genera_variable
```

## Individual:Specific_Identifier

```{r}
genus_individual_presence <- otu_long %>%
  group_by(genus, specific_identifier) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_individuals_variable <- n_distinct(metdat$specific_identifier)
```

```{r}
core_genera_individual <- genus_individual_presence %>%
  group_by(genus) %>%
  summarise(n_individuals_present = sum(present),
            prop_individuals = n_individuals_present / n_individuals_variable) %>%
  filter(prop_individuals >= 0.50) %>%
  arrange(desc(prop_individuals))

core_genera_individual
```

## Individual:Sample

```{r}
genus_individual_presence <- otu_long %>%
  group_by(genus, sample) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_individuals_variable <- n_distinct(metdat$sample)
```

```{r}
core_genera_individual <- genus_individual_presence %>%
  group_by(genus) %>%
  summarise(n_individuals_present = sum(present),
            prop_individuals = n_individuals_present / n_individuals_variable) %>%
  filter(prop_individuals >= 0.50) %>%
  arrange(desc(prop_individuals))

core_genera_individual
```


## Body Site

```{r}
genus_site_presence <- otu_long %>%
  group_by(genus, bodysite_standard) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_site <- n_distinct(metdat$bodysite_standard)
```

```{r}
core_genera_site <- genus_site_presence %>%
  group_by(genus) %>%
  summarise(n_site_present = sum(present),
            prop_site = n_site_present / n_site) %>%
  filter(prop_site >= 0.50) %>%
  arrange(desc(prop_site))

core_genera_site
```


## individual and bodysite

```{r}
genus_ibs_presence <- otu_long %>%
  group_by(genus, specific_identifier, bodysite_standard) %>%
  summarise(present = any(count > 0), .groups = "drop")
```

```{r}
n_ibs <- metdat |> 
  distinct(bodysite_standard, specific_identifier) |> 
  nrow()
```



```{r}
core_genera_ibs <- genus_ibs_presence %>%
  group_by(genus) %>%
  summarise(n_present = sum(present),
            prop= n_present / n_ibs) %>%
  filter(prop >= 0.50) %>%
  arrange(desc(prop))

core_genera_ibs
```

## Site Specific Core


```{r}
core_genera_by_site <- genus_ibs_presence %>%
  group_by(bodysite_standard, genus) %>%
  summarise(n_individuals_present = sum(present),
            n_individuals_total = n_distinct(specific_identifier),
            prop_individuals = n_individuals_present / n_individuals_total,
            .groups = "drop") %>%
  filter(prop_individuals >= 0.50) %>%
  arrange(bodysite_standard, desc(prop_individuals))

core_genera_by_site
```

```{r}
metdat |> 
  count(bodysite_standard)
```

```{r}
core_genera_by_site |> 
  filter(bodysite_standard == "cecum")
```

```{r}
core_genera_by_site |> 
  filter(bodysite_standard == "colon")
```

```{r}
split_by_site <- function(df, site_col = "bodysite_standard") {
  sites <- unique(df[[site_col]])
  
  for (s in sites) {
    obj_name <- paste0("core_genera_", make.names(s))  # sanitizes spaces/special chars
    assign(obj_name, df %>% filter(.data[[site_col]] == s), envir = .GlobalEnv)
  }
  
  message(paste("Created objects:", paste0("core_genera_", make.names(sites), collapse = ", ")))
}

split_by_site(core_genera_by_site)

# Now you have core_genera_colon, core_genera_cecum, etc. directly in your environment
core_genera_colon
```

```{r}
write_csv(core_genera_cecum, "asv_core_cecum.csv")
write_csv(core_genera_digesta, "asv_core_digesta.csv")
write_csv(core_genera_colon, "asv_core_colon.csv")
write_csv(core_genera_duodenum, "asv_core_duodenum.csv")
write_csv(core_genera_feces, "asv_core_feces.csv")
write_csv(core_genera_ileum, "asv_core_ileum.csv")
write_csv(core_genera_jejunum, "asv_core_jejunum.csv")
write_csv(core_genera_mucosa, "asv_core_mucosa.csv")
```

